FROM ghcr.io/graalvm/native-image-community:21 AS build
WORKDIR /app

RUN microdnf install -y findutils && microdnf clean all

COPY gradle gradle
COPY gradlew settings.gradle build.gradle ./
RUN chmod +x gradlew
RUN ./gradlew dependencies --configuration runtimeClasspath --no-daemon

COPY src src
RUN ./gradlew nativeCompile --no-daemon -x test

FROM debian:12-slim
WORKDIR /app
COPY --from=build /app/build/native/nativeCompile/demo .
EXPOSE 8080
ENTRYPOINT ["/app/demo"]
